### PR TITLE
chore: Update @jspm/generator@2.0.0

### PR DESCRIPTION
**Pull request by JayaKrishnaNamburu**
### Chore

Update the @jspm/generator to the latest version

### CODE REVIEW

**Comment by JayaKrishnaNamburu** [comment]
@yowainwright any thoughts on the CI failure for the `ensureDirSync` now. The tests seems to work for me in local

**Comment by yowainwright** [comment]
@JayaKrishnaNamburu do we need to do something new to create the `.cache/` directory in the Github action with  `@jspm/generator@2.0.0`?

**Comment by JayaKrishnaNamburu** [comment]
I don't think they are related, maybe `ensureDirSync` is not creating the nested paths in the path now. If missing, and checking only the last folder/file from given path ?

**Comment by yowainwright** [comment]
@JayaKrishnaNamburu you're onto something
- Same failure [here](https://github.com/jspm/node-importmap-http-loader/pull/25)

**Review by yowainwright — APPROVED** [review]
Looks good-to-go @JayaKrishnaNamburu 🔥

**Pull request merged**
